theme: jekyll-theme-minimal
name: Ange Crespo, Engineer
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title
environment: production

plugins:
  - jekyll-sitemap

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: https-ange-crespo-github-io
url: ange-crespo.github.io
t:
  en:
    logo:
      url: "emojione:flag-for-united-kingdom"
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/"
    cv:
      name: "CV"
      url: "/cv/"
    blog: 
      name: "Blog"
      url: '/blog/'
  fr:
    logo:
      url: "emojione:flag-for-france"
    home:
      name: "Accueil"
      url: "/fr"
    about:
      name: "À propos"
      url: "/about/fr"
    cv:
      name: "CV"
      url: "/cv/fr"
    blog:
      name: "Blog"
      url: "/blog/fr"
  zh:
    home:
      name: "首页"
      url: "/首页/"
    about:
      name: "关于"
      url: "/关于/"

tr :
  en:
    logo:
      url: "emojione:flag-for-united-kingdom"
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/"
    cv:
      name: "CV"
      url: "/cv/"
    blog: 
      name: "Blog"
      url: '/blog/'
    link:
      name: "Links"
    written:
      name: "Written the"
    fb:
      name: ""
    insta:
      name: ": Follow Me !"
    malt:
      name: ""
    whatsapp:
      name: "What'sApp message me"
    tel: 
      name: ""
    email:
      name: ""
    tip:
        name: ": Tip me !"
    github:
      name: ""
    linkedin:
      name: ""
    

  fr:
    logo:
      url: "emojione:flag-for-france"
    home:
      name: "Accueil"
      url: "/fr"
    about:
      name: "À propos"
      url: "/about/fr"
    cv:
      name: "CV"
      url: "/cv/fr"
    blog:
      name: "Blog"
      url: "/blog/fr"
    link:
      name: "Liens"
    written:
      name: "Écrit le"
    fb:
      name: ""
    insta:
      name: ": Follow Moi !"
    malt:
      name: ""
    whatsapp:
      name: "What'sApp message"
    tel: 
      name: ""
    email:
      name: ""
    tip:
        name: ": Soutient moi !"
    github:
      name: ""
    linkedin:
      name: ""
  zh:
    home:
      name: "首页"
      url: "/首页/"
    about:
      name: "关于"
      url: "/关于/"
