theme: jekyll-theme-minimal
name: Ange Crespo, Engineer
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title
environment: production

plugins:
  - jekyll-sitemap

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: https-ange-crespo-github-io
url: ange-crespo.github.io

t:
  en:
    logo:
      url: "emojione:flag-for-united-kingdom"
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/"
    cv:
      name: "CV"
      url: "/cv/"
    blog: 
      name: "Blog"
      url: '/blog/'
    
  fr:
    logo:
      url: "emojione:flag-for-france"
    home:
      name: "Accueil"
      url: "/fr"
    about:
      name: "À propos"
      url: "/about/fr"
    cv:
      name: "CV"
      url: "/cv/fr"
    blog:
      name: "Blog"
      url: "/blog/fr"
  zh:
    home:
      name: "首页"
      url: "/首页/"
    about:
      name: "关于"
      url: "/关于/"

tr :
  en:
    logo:
      url: "emojione:flag-for-united-kingdom"
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/"
    cv:
      name: "CV"
      url: "/cv/"
    blog: 
      name: "Blog"
      url: '/blog/'
    link:
      name: "Links"
    written:
      name: "Written the"
    fb:
      name: ""
    insta:
      name: ": Follow Me !"
    malt:
      name: ""
    whatsapp:
      name: "What'sApp message me"
    tel: 
      name: ""
    email:
      name: ""
    tip:
        name: ": Tip me !"
    github:
      name: ""
    linkedin:
      name: ""
    author:
      name: "Details about the author"

  fr:
    logo:
      url: "emojione:flag-for-france"
    home:
      name: "Accueil"
      url: "/fr"
    about:
      name: "À propos"
      url: "/about/fr"
    cv:
      name: "CV"
      url: "/cv/fr"
    blog:
      name: "Blog"
      url: "/blog/fr"
    link:
      name: "Liens"
    written:
      name: "Écrit le"
    fb:
      name: ""
    insta:
      name: ": Me suivre!"
    malt:
      name: ""
    whatsapp:
      name: "What'sApp message"
    tel: 
      name: ""
    email:
      name: ""
    tip:
        name: ": Me soutenir!"
    github:
      name: ""
    linkedin:
      name: ""
    author:
      name: "Détails sur l'auteur"
  zh:
    home:
      name: "首页"
      url: "/首页/"
    about:
      name: "关于"
      url: "/关于/"


author:

  ange:
    img_url : "selfiecadree.jpg"
    name : "Ange Crespo"
    slogan : "La French Touch"
    tel : 
      is_displayed : "True"
      display : "(+33) 0766702406"
      href : "+33766702406"
    email:
      is_displayed : "True"
      display : "ange.crespo@hotmail.fr"
      href : "ange.crespo@hotmail.fr"
    company:
      name : "#Polyfaces"
      line1 : "5, Allée de la Source Thermale,"
      line2 : " 11260 Campagne-sur-Aude"
      line3 : "France"
    instagram:
      is_displayed : "True"
      href : "https://www.instagram.com/angcrsp/"
    facebook:
      is_displayed : "True"
      href : "https://www.facebook.com/ang.crp"
    malt :
      is_displayed : "True"
      href : "https://www.malt.fr/profile/angecrespo"
    linkedin :
      is_displayed : "True"
      href : "https://www.linkedin.com/in/angecrespo"
    github:
      is_displayed: "True"
      href : "https://ange-crespo.github.io/"
  colin:
    name : "Colin Bois"
    slogan : ""
    email:
      is_displayed : "True"
      display : "colin.bois@rocketmail.com"
      href : "colin.bois@rocketmail.com"
  thomas:
    name: "Thomas Kalensky"
  laureline:
    name : "Laureline Lamoureux"
    slogan : ""
    email:
      is_displayed : "True"
      display : "laurelinelamoureux@gmail.com"
      href : "laurelinelamoureux@gmail.com"
    site:
      is_displayed : "True"
      display : "Chamoureux.fr"
      href : "https://www.chamoureux.fr/"
    tel : 
      is_displayed : "False"
      display : "(+33) 0628761564"
      href : "+33628761564"
    instagram:
      is_displayed : "True"
      href : "https://www.instagram.com/chamoureux31/"